//
// Created by bison on 9/26/18.
//

AddWeaponTemplate(context, "Dagger", 2, WS_SMALL, 1, "1D4", 1, WC_SHARP);
AddWeaponTemplate(context, "Battle Axe", 7, WS_MEDIUM, 7, "1D8", 1, WC_SHARP);
AddWeaponTemplate(context, "Shortsword", 6, WS_SMALL, 3, "1D6", 1, WC_SHARP);
AddWeaponTemplate(context, "Longsword", 10, WS_MEDIUM, 4, "1D8", 1, WC_SHARP);
AddWeaponTemplate(context, "Two-handed Sword", 18, WS_LARGE, 10, "1D10", 1, WC_SHARP);
AddWeaponTemplate(context, "Baseball Bat", 18, WS_LARGE, 10, "1D10+2", 1, WC_BLUNT);
AddWeaponTemplate(context, "9mm Pistol", 25, WS_MEDIUM, 2, "1D6", 2, WC_GUN);
AddWeaponTemplate(context, "Rifle", 60, WS_LARGE, 3, "1D8", 4, WC_GUN);